---
title: "Project 1.1"
author: "Roxy Campher"
format: pdf
editor: visual
---

# Project 1.1 - Comparing Models for Daily Sampled South African Market Index Data

## Exploratory Data Analysis

```{r}
#| echo: false

# load required libraries:
library(ggplot2)
library(dplyr)
library(readxl)
```

```{r}
# Read in the data
albi <- read_excel(
  "data/PT-DATA-ALBI-JIBAR-JSEIND-Daily-1994-2017.xlsx",
  skip = 4,
  col_names = FALSE
)

# Selecting the relevant columns
albi <- albi |>
  select(
    Date = ...3,
    Index = ...4
  )

# Reorder so the oldest comes first
albi <- albi |>
  arrange(Date)

# There are many NAs before 2006 so we will shift the window to be from 2006 - 2017
albi$Date <- as.Date(albi$Date)

albi_0616 <- albi |>
  filter(
    Date >= as.Date("2006-01-01"),
    Date <= as.Date("2016-12-31")
  )

#View(albi_0616)
range(albi_0616$Date)

# Create the return series
albi_0616 <- albi_0616 |>
  mutate(
    Return = 100 * (log(Index) - log(lag(Index)))
  )

# Remove NA
albi_returns <- na.omit(albi_0616$Return)

albi_ts <- ts(
  albi_0616$Index,
  start = c(2006, 1),
  frequency = 252
)

plot(albi_ts, main = "ALBI Index Levels.", xlab = "Time (daily)", ylab = "Index Level", col = "blue")
```
